/** Paths estáticos bajo `public/jec/` (año 2025 → prototipo 2026). */

export const jecAssets = {
  favicon: "/jec/favicon.svg",
  background: {
    hero: "/jec/background/fondo1.webp",
    secondary: "/jec/background/fondo2.webp",
    tertiary: "/jec/background/fondo3.webp",
    pisada: "/jec/background/background.webp",
  },
  logos: {
    jecWhiteSvg: "/jec/logos/logoblanco.svg",
    jecWhitePng: "/jec/logos/logoblanco.png",
    jecBlackPng: "/jec/logos/logonegro.png",
    ivsWhite: "/jec/logos/logoVSblanco.png",
    ivsBlack: "/jec/logos/logoVSnegro.png",
  },
  oradores: {
    florMraida: "/jec/oradores/flormraida.webp",
    ezequielMangonnet: "/jec/oradores/ezequielmango.webp",
    josiasGarcia: "/jec/oradores/josias.webp",
    nataliaSpetale: "/jec/oradores/nati.webp",
    ezequielRossini: "/jec/oradores/eze.webp",
    juanPabloSosa: "/jec/oradores/juan.webp",
  },
  personaje: {
    llama: "/jec/personaje/llama.svg",
    orando: "/jec/personaje/fuegoorando.svg",
    festejando: "/jec/personaje/fuegofestejando.png",
    apuntando: "/jec/personaje/fuegoapuntandoizq.png",
  },
  hero: {
    finale: "/jec/hero/hero.png",
  },
  recursos: {
    huellas: "/jec/recursos/huellas.svg",
    pngsTransparente: {
      "01": "/jec/recursos/pngs-transparente-01.svg",
      "02": "/jec/recursos/pngs-transparente-02.svg",
      "03": "/jec/recursos/pngs-transparente-03.svg",
      "04": "/jec/recursos/pngs-transparente-04.svg",
      "05": "/jec/recursos/pngs-transparente-05.svg",
      "06": "/jec/recursos/pngs-transparente-06.svg",
      "07": "/jec/recursos/pngs-transparente-07.svg",
      "08": "/jec/recursos/pngs-transparente-08.svg",
      "09": "/jec/recursos/pngs-transparente-09.svg",
      "10": "/jec/recursos/pngs-transparente-10.svg",
      "11": "/jec/recursos/pngs-transparente-11.svg",
      "12": "/jec/recursos/pngs-transparente-12.svg",
      "13": "/jec/recursos/pngs-transparente-13.svg",
      "14": "/jec/recursos/pngs-transparente-14.svg",
      "15": "/jec/recursos/pngs-transparente-15.svg",
      "16": "/jec/recursos/pngs-transparente-16.svg",
      "17": "/jec/recursos/pngs-transparente-17.svg",
      "18": "/jec/recursos/pngs-transparente-18.svg",
      "19": "/jec/recursos/pngs-transparente-19.svg",
      "20": "/jec/recursos/pngs-transparente-20.svg",
      "21": "/jec/recursos/pngs-transparente-21.svg",
      "22": "/jec/recursos/pngs-transparente-22.svg",
      "23": "/jec/recursos/pngs-transparente-23.svg",
      "24": "/jec/recursos/pngs-transparente-24.svg",
      "25": "/jec/recursos/pngs-transparente-25.svg",
      "26": "/jec/recursos/pngs-transparente-26.svg",
      "27": "/jec/recursos/pngs-transparente-27.svg",
      "28": "/jec/recursos/pngs-transparente-28.svg",
    },
  },
} as const;
